---
title: "Assignment 2"
author: "Tim But, Mehmet Bedirhan Gursoy, Vincentas Ryliskis, group 035"
date: "20 November 2023"
output: pdf_document
fontsize: 11pt
highlight: tango
---
# Setting a Seed

In order to ensure that the results in this report are reproducible, seed (123) was used when generating random numbers.
```{r message=FALSE, warning=FALSE}
set.seed(123)
```
# Task 1

## a)

In order to achieve a 95% confidence interval, we will use a Z-value of $Z = 1.96$, and in order to achieve a margin of error of 2%, we will use a value of $E = 0.02$. Due to the fact that we are working with a proportion, our calculation for the number (n) of surveyed flights should look as follows:

$n = (Z\frac{\sqrt{p(1-p)}}{E})^2$

Because we do not have a value for p, we can assume that p is equal to 0.5 - the value at which $p(1-p)$ will have it's highest value. Therefore, after accounting for all values, we get:

$n = (1.96\frac{\sqrt{0.5(1-0.5)}}{0.02})^2 = (1.96\frac{\sqrt{0.25}}{0.02})^2 = 2401$

Therefore, we need 2401 samples in order to get the desired margin of error over the desired confidence interval

## b) 

As the desired confidence interval and Z score remain the same as in part a), we can keep the previously used values of $E = 0.02$ and $Z = 1.96$. Additionally, the formula for calculating n stays the same:

$n = (Z\frac{\sqrt{p(1-p)}}{E})^2$

However, we are given a value for p in this part: 0.9. For this value of p, the calculation for n looks as follows:

$n = (1.96\frac{\sqrt{0.9(1-0.9)}}{0.02})^2 = (1.96\frac{\sqrt{0.09}}{0.02})^2 = 864.36$

Therefore, we need 865 samples in order to get the desired margin of error over the desired confidence interval


# Task 2

In task 2, we are given the following values:

$\bar{x}_1 = 1124.3$

$\bar{x}_2 = 1118.1$

$s_d = 57.8$

$n = 30$

In order to find a confidence interval for $\bar{x}_1 - \bar{x}_2$, we will use the formula for two dependent samples, as the two sets are of first and second-born twins:

$[\bar{d} - t_{n - 1, \alpha/2}\frac{s_d}{\sqrt{n}}, \bar{d} + t_{n-1, \alpha/2}\frac{s_d}{\sqrt{n}}]$

Where $\bar{d} = \bar{x}_1 - \bar{x}_2 = 6.2$. Therefore, when we substitute the numbers, we get:

$[6.2 - t_{29, 0.05}\frac{57.8}{\sqrt{30}}, 6.2 + t_{29, 0.05}\frac{57.8}{\sqrt{30}}]$

Further evaluating the numbers (and critical t values) gives us:

$[6.2 - 1.699\frac{57.8}{\sqrt{30}}, 6.2 + 1.699\frac{57.8}{\sqrt{30}}] = [6.2 - 17.929, 6.2 + 17.929]$

Resulting in a confidence interval of:

$[-11.729, 6.2 + 24.129]$


# Task 3
Test Claim: Whether there is a difference in the population mean volumes of first- and
second-born babies.

H_0 = \mu1 != \mu2
H_1 = \mu1 = \mu2
significance_level = 0.05

n1 = 25
x1 = 1131.3
s1 = 129.0

n1 = 20
x2 = 1123.8
s2 = 127.2

value of test_statistic:

t2 = (1131.3-1123.8)/sqrt(((129^2)/25)+((127.2^2)/20))

t2 = 0.078

n = min(25-1, 20-1) = min(24, 19) = 19

t19,0.025 = 1.729

since 0.078 < 1.729 and 0.078 > -1.729 we faile to reject H0.

There is not sufficient evidence to warrant rejection of the claim whether there is a difference in the population mean volumes of first- and
second-born babies
# Task 4

# Task 5